config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  # for STRIPE
  resources :charges

  resources :abouts
  devise_for :users
  resources :orders
  resources :hire_classes
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Cart
  resource :cart, only: [:show]
  resources :order_items, only: %i[create update destroy]

  ActiveAdmin.routes(self)
  resources :accessories
  resources :customers
  resources :hirelings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'search_results', to: 'search#results', as: 'search_results'
  get ':hire_class', to: 'hirelings#hire_class'
  get ':accessory', to: 'accessory#id'


  root to: 'accessories#index'
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/accessory.rb
# frozen_string_literal: true

class Accessory < ApplicationRecord
  validates :accessory_name, :description, :cost, :stock, presence: true
  validates :accessory_name, uniqueness: true
  paginates_per 5

  has_many :order_items

  default_scope { where(active: true) }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  validates :f_name, :l_name, :email, presence: true
  validates :email, uniqueness: true
end

app/models/hire_class.rb
# frozen_string_literal: true

class HireClass < ApplicationRecord
  has_many :hirelings

  validates :name, uniqueness: true

  def class_name
    name
  end

  def class_description
    description
  end
end

app/models/hireling.rb
# frozen_string_literal: true

class Hireling < ApplicationRecord
  belongs_to :hire_class
  validates :name, :class, presence: true
  validates :name, uniqueness: true

  mount_uploader :image, ImageUploader
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  #belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  #validates :accessories_ordered, :price_total, presence: true
  #validates :price_total, numericality: true

  def sub_total
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:total] = sub_total
  end
end

app/models/order_accessory.rb
# frozen_string_literal: true

class OrderAccessory < ApplicationRecord
  
  validates :order_id_fk, :accessory_id_fk, :purchase_price, presence: true
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :accessory
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :accessory_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      accessory.cost
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def accessory_present
    errors.add(:accessory, 'is not valid or is not active.') if accessory.nil?
  end

  def order_present
    erros.add(:order, 'is not a valid order.') if order.nil?
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
# frozen_string_literal: true

class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/hirelings_helper.rb
module HirelingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.sub_total} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_nav.html.erb
<%# <%= link_to 'hireling', root_path, class: 'navbar-brand' %>
<%# <%= link_to 'accessory', root_path, class: 'navbar-brand' %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "DnD shop!", accessories_path, class:"navbar-brand" %>
  <%# <a class="navbar-brand" href="#">D n D</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
       <%= link_to "Gear UP!", accessories_path, class:"sr-only" %>
        <%# <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> %>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> %>
      <li class="nav-item dropdown">
        <div class="nav-link dropdown-toggle"id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Hireling Classes
        </div>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% @hire_class_navs.each do |hire_class_nav| %>
            <%= link_to hire_class_nav.class_name, hire_class_nav.class_name, class:"dropdown-item" %>
            <div class="dropdown-divider"></div>
          <% end %>
          <%= link_to "All Classes", hirelings_path, class:"dropdown-item" %>

        </div>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
    <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>

</form>
  </div>
</nav>
<%= form_tag(search_results_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DAndD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/nav' %>
  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
      </div>
      <div class="col-xs-6 text-right">

      </div>
    </div>
    <hr>
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>